# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: self
    - name: Checkout Docker MySQL Repository
      uses: actions/checkout@v2
      with:
        repository: 'm0rph2us/docker-mysql'
        path: 'docker-mysql'
    - name: Checkout Proper Docker MySQL Branch
      run: echo $GITHUB_HEAD_REF && git checkout $(echo $GITHUB_HEAD_REF | cut -d'/' -f1)/${GITHUB_HEAD_REF##*/}
      working-directory: 'docker-mysql'
      continue-on-error: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: self
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: self
